security_group:
  request_id: RQ-002
  business_justification: >
    Create security-group for dumpydog API us-east-1 privatelink in us-west-2
  accountId: 6666666
  region: us-west-2
  vpc_id: vpc-014a623d564aa2524
  serviceType: privatelink-consumer
  serviceName: com.amazonaws.vpce.us-east-1.vpce-svc-064ea718f8d0ead77
  thirdpartyName: dumpydog
  thirdPartyID: 123456
rules:
  - request_id: RQ-002
    business_justification: >
        Create access from acct-1 intranet nat gateway to dumpydog api vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-bbb
      region: us-west-2
      ips:
        - 10.1.1.1/32
        - 10.2.1.1/32
        - 10.3.1.1/32
    protocol: tcp
    port: 443
    appid: ssl
    url: https://api.dumpydoghq.com
    enable_palo_inspection: true
