security_group:
  request_id: RQ-004
  business_justification: >
    Create security-group for MongoDB online archive privatelink in us-west-2
  accountId: 6666666
  region: us-west-2
  vpc_id: vpc-ddd
  serviceType: privatelink-consumer
  serviceName: com.amazonaws.vpce.us-west-2.vpce-svc-mongodb2349873
  thirdpartyName: MongoDB
  thirdPartyID: 789456
rules:
  - request_id: RQ-004
    business_justification: >
        Create access from acct-1 intranet nat gateway to mongodb online archive vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-bbb
      region: us-west-2
      ips:
        - 10.1.1.1/32
        - 10.2.1.1/32
        - 10.3.1.1/32
    protocol: tcp
    port: 443
    appid: ssl
    url: "https://atlas-online-archive-mongodb2349873-company1.a.query.mongodb.net"
    enable_palo_inspection: true