request_id: req-20240428-xyz
submitted_by: jeffreywoods@example.com
submitted_at: 2024-04-28T14:00:00Z

overall_business_justification: >
  Enable management connectivity for testing palo alto providers. 

requests:
  - business_justification: >
      Allow UI access from home. 
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: [$HOME_IP]
    destination:
      account_id: $TEST_ACCOUNT
      vpc_id: $TEST_VPC
      region: "us-west-2"
      security_group_ids:
      - $PALO_VM_SG_ID
      ips: ["192.168.1.100/32"]
    protocol: tcp
    port: 443
    appid: ssl
    url:  

  - business_justification: >
      Allow SSH access from home. 
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: [$HOME_IP]
    destination:
      account_id: $TEST_ACCOUNT
      vpc_id: $TEST_VPC
      region: "us-west-2"
      security_group_ids:
      - $PALO_VM_SG_ID
      ips: ["192.168.1.100/32"]
    protocol: tcp
    port: 22
    appid: ssl
    url:  

  - business_justification: >
      Allow ICMP access from home. 
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: [$HOME_IP]
    destination:
      account_id: $TEST_ACCOUNT
      vpc_id: $TEST_VPC
      region: "us-west-2"
      security_group_ids:
      - $PALO_VM_SG_ID
      ips: ["192.168.1.100/32"]
    protocol: any
    port: any
    appid: ssl
    url:  

  - business_justification: >
      Allow ICMP access from home. 
    source:
      account_id: $TEST_ACCOUNT
      vpc_id: $TEST_VPC
      region: "us-west-2"
      security_group_ids:
      - $PALO_VM_SG_ID
      ips: ["192.168.1.100/32"]
    destination:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: any
    protocol: any
    port: any
    appid: ssl
    url:  