security_group:
  request_id: RQ-001
  business_justification: >
    Create security-group for datadog API us-east-1 privatelink in us-east-1
  accountId: 6666666
  region: us-east-1
  vpc_id: vpc-05ebefacb081c3018
  serviceType: privatelink-consumer
  serviceName: com.amazonaws.vpce.us-east-1.vpce-svc-064ea718f8d0ead77
  thirdpartyName: port-range-rule
  thirdPartyID: 123456
rules:
  - request_id: RQ-001
    business_justification: >
        Create access from acct-1 intranet nat gateway to datadog api vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-aaa
      region: us-east-1
      ips:
        - 10.50.0.0/24
    protocol: tcp
    port: 9000-10000
    appid: ssl
    url: https://api.datadoghq.com
    enable_palo_inspection: true
  - request_id: RQ-002
    business_justification: >
        Create access from acct-1 intranet nat gateway to datadog api vpc-endpoint. 
    source:
      account_id: 111122223333
      vpc_id: vpc-aaa
      region: us-east-1
      ips:
        - 10.58.1.1/32
    protocol: tcp
    port: 8010-8020
    appid: ssl
    url: https://api.datadoghq.com
    enable_palo_inspection: true