security_group:
  request_id: RQ-006
  business_justification: >
    Create security-group to expose `app-zyx` behind NLB over PrivateLink in us-west-2.
  accountId: 6666666
  region: us-west-2
  vpc_id: vpc-014a623d564aa2524
  serviceType: privatelink-provider
  internalAppID: app-zyx

rules:
  - request_id: RQ-006
    business_justification: >
      Allow partner nlb health checks and backend connectivity for app-zyx. 
    destination:
      ips:
        - 172.20.1.1/32
        - 172.21.1.1/32
        - 172.22.1.1/32
    port: 443
    protocol: tcp
    url: app-zyx.us-west-2.mycompany.com
    appid: ssl
    enable_palo_inspection: true
