security_group:
  request_id: RQ-005
  business_justification: >
    Create security-group to expose `app-zyx` behind NLB over PrivateLink in us-east-1.
  accountId: 6666666
  region: us-east-1
  vpc_id: vpc-ccc
  serviceType: privatelink-provider
  internalAppID: app-zyx

rules:
  - request_id: RQ-005
    business_justification: >
      Allow partner nlb health checks and backend connectivity for app-zyx. 
    destination:
      ips:
        - 172.16.1.1/32
        - 172.17.1.1/32
        - 172.18.1.1/32
    port: 443
    protocol: tcp
    url: app-zyx.us-east-1.mycompany.com
    appid: ssl
    enable_palo_inspection: true
