  - request_id: 1234687
    business_justification: >
      Allow UI access from home. 
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: ["1.1.1.1/32"]
    destination:
      account_id: 12345678
      vpc_id: vpc-0c9a555406867d5da
      region: "us-west-2"
      security_group_ids:
      - sg-0b5d6e2811145808d
      ips: []
    protocol: tcp
    port: 443
    appid: ssl
    url:  

  - request_id: 1234687
    business_justification: >
      Allow SSH access from home. 
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: ["1.1.1.1/32"]
    destination:
      account_id: 12345678
      vpc_id: vpc-0c9a555406867d5da
      region: "us-west-2"
      security_group_ids:
      - sg-0b5d6e2811145808d
      ips: []
    protocol: tcp
    port: 22
    appid: ssl
    url:  

  - request_id: 1234687
    business_justification: >
      Allow ICMP access from home. 
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: ["1.1.1.1/32"]
    destination:
      account_id: 12345678
      vpc_id: vpc-0c9a555406867d5da
      region: "us-west-2"
      security_group_ids:
      - sg-0b5d6e2811145808d
      ips: []
    protocol: any
    port: any
    appid: ssl
    url:  

  - request_id: 1234687
    business_justification: >
      Allow egress access from palo. 
    source:
      account_id: 12345678
      vpc_id: vpc-0c9a555406867d5da
      region: "us-west-2"
      security_group_ids:
      - sg-0b5d6e2811145808d
      ips: []
    destination:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: ["0.0.0.0/0"]
    protocol: any
    port: any
    appid: ssl
    url:  
  
  - request_id: 1234687
    business_justification: >
      EC2 instance needs HTTPS access to thirdparty endpoint.
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
        - "sg-0b7029dc87dbcb848"
      ips: ["192.168.1.18/32"]
    destination:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
        - "sg-01057cb19af0373d7"
      ips: ["100.64.0.198/32"]
    protocol: tcp
    port: 443
    appid: ssl
    url_category: api.datadoghq.com
    thirdPartyID: 123456
    thirdPartyName: DataDog
    enable_palo_inspection: true

  - request_id: 1234687
    business_justification: >
      EC2 needs to connect to aws service vpc-endpoints via PrivateLink.
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
        - "sg-0b7029dc87dbcb848"
      ips: []
    destination:
      account_id:
      vpc_id: 
      region:
      security_group_ids:
        - "sg-0dfca87f31291ec64"
      ips: []
    protocol: tcp
    port: 443
    appid: ssl
    host: ec2.us-west-2.amazonaws.com

  # From issue #86
  
  - request_id: 1234687
    business_justification: >
      Allow HTTPS access from EC2 to DooDooDog
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
        - sg-0b7029dc87dbcb848
      ips: ["192.168.1.18/32"]
    destination:
      account_id: 
      vpc_id: 
      region: "us-west-2"
      security_group_ids:
        - sg-0b79868485b793c17
      ips: ["100.64.0.199/32"]
    protocol: tcp
    port: 443
    appid: ssl
    url:  
    enable_palo_inspection: true
    thirdPartyID: 6969
    thirdPartyName: DooDooDog
    region: us-west-2

  # From issue #90
  
  - request_id: 1234687
    business_justification: >
      Allow HTTPS access from EC2 to realoksi vpc-endpoint
    source:
      security_group_ids:
        - sg-0b7029dc87dbcb848
      ips: ["192.168.1.18/32"]
    destination:
      security_group_ids:
        - sg-04666e610aa2d5bb0
      ips: ["100.64.0.170/32"]
    protocol: tcp
    port: 443
    appid: ssl
    enable_palo_inspection: true
    thirdPartyID: 68594
    thirdPartyName: realoksi
    region: us-west-2

  # From issue #94
  
  - request_id: 1234687
    business_justification: >
      Allow UI Access from Alternate Source subnet
    source:
      account_id: 
      vpc_id: 
      region: 
      security_group_ids:
      ips: ["1.1.1.1/32"]
    destination:
      account_id: 12345567
      vpc_id: vpc-0c9a555406867d5da
      region: "us-west-2"
      security_group_ids:
        - sg-0b5d6e2811145808d 
      ips: []
    protocol: tcp
    port: 443
    appid: ssl
    url:  
