  - request_id: req123456
    business_justification: >
      Create SG for Thirdparty MaxBarb 
    thirdpartyName: MaxBarb
    thirdpartyId: 474833
    accountId: 6666666
    vpcId: vpc-0c9a555406867d5da
    region: eu-west-2