name: Create PrivateLink Consumer Security Group
description: Request to create a new security group for a PrivateLink consumer service
title: "[SG] Create PrivateLink Consumer for: "
labels: ["sg-request", "privatelink-consumer"]
assignees:
  - netops-team

body:
  - type: markdown
    attributes:
      value: |
        ## PrivateLink Consumer Request
        Use this template to request a new security group for accessing a third-party service via AWS PrivateLink.
        
  - type: dropdown
    id: region
    attributes:
      label: AWS Region
      description: Select the AWS region for this request
      options:
        - us-east-1
        - us-west-2
    validations:
      required: true
      
  - type: dropdown
    id: vpc_id
    attributes:
      label: VPC ID
      description: Select the VPC where the security group will be created
      options:
        - vpc-0f0330876868cc9d2 (us-east-1)
        - vpc-014a623d564aa2524 (us-west-2)
    validations:
      required: true
      
  - type: input
    id: third_party_name
    attributes:
      label: Third-Party Name
      description: Name of the third-party service provider
      placeholder: "e.g., Datadog, MongoDB Atlas"
    validations:
      required: true
      
  - type: input
    id: third_party_id
    attributes:
      label: Third-Party ID
      description: Tracking ID for the third-party (if applicable)
      placeholder: "e.g., 123456"
    validations:
      required: true
      
  - type: input
    id: service_name
    attributes:
      label: VPC Endpoint Service Name
      description: AWS PrivateLink service name to connect to
      placeholder: "e.g., com.amazonaws.vpce.us-east-1.vpce-svc-0123456789abcdef"
    validations:
      required: true
      
  - type: input
    id: request_id
    attributes:
      label: Request ID
      description: Tracking ID for this request
      placeholder: "e.g., RQ-001"
    validations:
      required: true
      
  - type: textarea
    id: business_justification
    attributes:
      label: Business Justification
      description: Explain why this access is needed
      placeholder: "e.g., Need to connect to Datadog API via PrivateLink for secure monitoring"
    validations:
      required: true
      
  - type: textarea
    id: yaml_config
    attributes:
      label: PrivateLink Consumer YAML
      description: Complete this YAML template with your request details
      value: |
        ```yaml
        security_group:
          request_id: YOUR-REQUEST-ID
          business_justification: >
            YOUR BUSINESS JUSTIFICATION HERE
          accountId: 6666666
          region: us-east-1  # or us-west-2
          vpc_id: vpc-0f0330876868cc9d2  # or vpc-014a623d564aa2524
          serviceType: privatelink-consumer
          serviceName: YOUR-SERVICE-NAME
          thirdpartyName: YOUR-THIRD-PARTY-NAME
          thirdPartyID: YOUR-THIRD-PARTY-ID
        rules:
          - request_id: YOUR-REQUEST-ID
            business_justification: >
                YOUR RULE JUSTIFICATION HERE
            source:
              account_id: YOUR-SOURCE-ACCOUNT-ID
              vpc_id: YOUR-SOURCE-VPC-ID
              region: YOUR-SOURCE-REGION
              ips:
                - 10.0.0.1/32
                - 10.0.0.2/32
            protocol: tcp
            port: 443
            appid: ssl
            url: https://your-service-url.com
            enable_palo_inspection: true
        ```
    validations:
      required: true