name: Auto-Close Stale Issues

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Close issues older than 24 hours
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
        run: |
          NOW=$(date -u +%s)

          gh issue list --state open --json number,createdAt \
          | jq -c '.[]' \
          | while read -r issue; do
              NUMBER=$(echo "$issue" | jq -r '.number')
              CREATED=$(echo "$issue" | jq -r '.createdAt')
              CREATED_TS=$(date -d "$CREATED" +%s)
              AGE_MINUTES=$(( (NOW - CREATED_TS) / 60 ))

              if [ "$AGE_MINUTES" -ge 1440 ]; then  # 24 hours
                echo "Closing stale issue #$NUMBER (age: $AGE_MINUTES minutes)"
                gh issue comment "$NUMBER" --body "🕓 Automatically closed after being open for more than 24 hours with no activity."
                gh issue close "$NUMBER"
              fi
            done
