name: terraform plan workflow

on:
  push:
    branches:
      - dev
      - looprefactorv3
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_HOME_IP: ${{ secrets.HOME_IP }}
  TF_VAR_ALTERNATE_SOURCE: ${{ secrets.ALTERNATE_SOURCE }}
  TF_VAR_palo_username: ${{ secrets.PALO_USERNAME }}
  TF_VAR_palo_password: ${{ secrets.PALO_PASSWORD }}
  TF_VAR_palo_hostname: ${{ secrets.PALO_HOSTNAME }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUCKET_KEY: ${{ secrets.BUCKET_KEY }}
  BUCKET_ENDPOINT: ${{ secrets.BUCKET_ENDPOINT }}
  BUCKET_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
  BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/drewpypro/kube-aws-istio:latest
    defaults:
      run:
        working-directory: infrastructure

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify Backend
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
        run: |
          aws --endpoint-url ${BUCKET_ENDPOINT} s3api head-object --bucket ${BUCKET_NAME} --key test/poop.txt || \
          (echo "❌ Backend validation failed. Check credentials or filepath." && exit 1)

      # - name: Inject IPs into policy YAML
      #   run: |
      #     # sed -i "s|\\\$HOME_IP|${{ secrets.HOME_IP }}|g" policies/us-west-2/rules.yaml
      #     # sed -i "s|\\\$ALTERNATE_SOURCE|${{ secrets.ALTERNATE_SOURCE }}|g" policies/us-west-2/rules.yaml
      #     IP=$(curl -s ifconfig.me)
      #     echo "Runner public IP: $IP"
      #     aws ec2 authorize-security-group-ingress \
      #       --region us-east-1 \
      #       --group-id "sg-0ab46ac1c9bfe7e7a" \
      #       --protocol tcp \
      #       --port "22-443" \
      #       --cidr "${IP}/32" > /dev/null
          
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${BUCKET_NAME}" \
            -backend-config="key=${BUCKET_KEY}" \
            -backend-config="endpoint=${BUCKET_ENDPOINT}" \
            -backend-config="access_key=${BUCKET_ACCESS_KEY_ID}" \
            -backend-config="secret_key=${BUCKET_SECRET_ACCESS_KEY}"

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan

      # - name: Cleanup SG rule
      #   if: always()
      #   run: |
      #     IP=$(curl -s ifconfig.me)
      #     echo "Runner public IP: $IP"
      #     if [[ -n "$IP" ]]; then
      #       echo "Revoking IP: $IP"
      #       aws ec2 revoke-security-group-ingress \
      #         --region us-east-1 \
      #         --group-id "sg-0ab46ac1c9bfe7e7a" \
      #         --protocol tcp \
      #         --port "22-443" \
      #         --cidr "${IP}/32" || echo "⚠️ Failed to revoke IP, possibly already removed."
      #     else
      #       echo "⚠️ IP variable not found. Skipping revoke."
      #     fi
